name: leitor_de_ebooks
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  google_fonts: ^6.1.0
  vocsy_epub_viewer: ^2.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  mocktail: ^1.0.1
  dio: ^5.3.3
  flutter_animate: ^4.2.0+1
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  # assets: 
    

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
